<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-05T23:52:52 PDT" name="Suite" finished-at="2022-09-05T23:55:16 PDT" duration-ms="144177">
    <groups>
    </groups>
    <test started-at="2022-09-05T23:52:52 PDT" name="Test" finished-at="2022-09-05T23:55:16 PDT" duration-ms="144177">
      <class name="TestCases.VerifyLoginTestCase">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestCases.VerifyLoginTestCase@53fdffa1]" started-at="2022-09-05T23:52:52 PDT" name="launchBrowser" finished-at="2022-09-05T23:53:39 PDT" duration-ms="46918" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="login()[pri:0, instance:TestCases.VerifyLoginTestCase@53fdffa1]" started-at="2022-09-05T23:53:39 PDT" name="login" finished-at="2022-09-05T23:53:44 PDT" duration-ms="5400" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:TestCases.VerifyLoginTestCase@53fdffa1]" started-at="2022-09-05T23:53:45 PDT" name="teardown" finished-at="2022-09-05T23:53:46 PDT" duration-ms="1678" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TestCases.VerifyLoginTestCase -->
      <class name="TestCases.VerifySignupTestCase">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestCases.VerifySignupTestCase@194bcebf]" started-at="2022-09-05T23:53:46 PDT" name="launchBrowser" finished-at="2022-09-05T23:53:57 PDT" duration-ms="10902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="Signup()[pri:0, instance:TestCases.VerifySignupTestCase@194bcebf]" started-at="2022-09-05T23:53:57 PDT" name="Signup" finished-at="2022-09-05T23:55:14 PDT" duration-ms="76556" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Free CRM Trial: Salesforce 30-Day  - Salesforce IN] but found [Free CRM Trial: Salesforce 30-Day Trial - Salesforce IN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Free CRM Trial: Salesforce 30-Day  - Salesforce IN] but found [Free CRM Trial: Salesforce 30-Day Trial - Salesforce IN]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Resources.commonUtilities.handleAssertions(commonUtilities.java:22)
at TestCases.VerifySignupTestCase.Signup(VerifySignupTestCase.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Signup -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:TestCases.VerifySignupTestCase@194bcebf]" started-at="2022-09-05T23:55:14 PDT" name="teardown" finished-at="2022-09-05T23:55:16 PDT" duration-ms="2452" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TestCases.VerifySignupTestCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
